#!/usr/bin/python3

import sys
import os

obracena_pismena = {
    'a': 'ɐ', 'b': 'q', 'c': 'ɔ', 'd': 'p', 'e': 'ǝ', 'f': 'ɟ', 'g': 'ƃ',
    'h': 'ɥ', 'i': 'ᴉ', 'j': 'ɾ', 'k': 'ʞ', 'l': 'l', 'm': 'ɯ', 'n': 'u',
    'o': 'o', 'p': 'd', 'q': 'b', 'r': 'ɹ', 's': 's', 't': 'ʇ', 'u': 'n',
    'v': 'ʌ', 'w': 'ʍ', 'x': 'x', 'y': 'ʎ', 'z': 'z', 'A': '∀', 'B': 'B',
    'C': 'Ɔ', 'D': 'D', 'E': 'Ǝ', 'F': 'Ⅎ', 'G': 'פ', 'H': 'H', 'I': 'I',
    'J': 'ſ', 'K': 'ʞ', 'L': '˥', 'M': 'W', 'N': 'N', 'O': 'O', 'P': 'Ԁ',
    'Q': 'Q', 'R': 'R', 'S': 'S', 'T': '┴', 'U': '∩', 'V': 'Λ', 'W': 'M',
    'X': 'X', 'Y': '⅄', 'Z': 'Z', '0': '0', '1': 'Ɩ', '2': 'ᄅ', '3': 'Ɛ',
    '4': 'ㄣ', '5': 'ϛ', '6': '9', '7': 'ㄥ', '8': '8', '9': '6', ',': "'",
    '.': '˙', '?': '¿', '!': '¡', '"': '„', "'": ',', '`': ',', '(': ')',
    ')': '(', '[': ']', ']': '[', '{': '}', '}': '{', '<': '>', '>': '<',
    '&': '⅋', '_': '‾',
}

def znak_chybi(text):
    for c in text:
        if c not in obracena_pismena:
            sys.stdout.write(''.join(obracena_pismena.get(c, c) for c in reversed(text)))
            sys.stdout.write('\n')
            exit(2)

def obrat(text):
    znak_chybi(text)
    if sys.stderr == 2:
        exit(2)
    else:
        return ''.join(obracena_pismena.get(c, c) for c in reversed(text)),0

def zpracuj(vstup):
    for line in vstup:
        print(obrat(line.rstrip())[0])


#zpracovani argumentu '-','--help' a pokud prepinac neexistuje
if len(sys.argv) > 1:
    for jmeno in sys.argv[1:]:
        if jmeno == "--help":
            print(f"Napoveda: ")
            print(f"-       Standardni vstup")
            print(f"name    Je-li zadano jmeno souboru, zpracuje tento soubor")
            break
        elif jmeno[0] == "-" and len(jmeno) > 1 and jmeno != "--help":
            sys.stderr.write(f"Prepinac {jmeno} neexistuje, viz --help\n")
            exit(1)
        else:
            if jmeno == '-':
                zpracuj(sys.stdin)
        if jmeno != '-':
            try:
                with open(jmeno,"r") as file:
                    zpracuj(file)
            except FileNotFoundError:
                print(f"File not found")
else:
    zpracuj(sys.stdin)
                                 